title: Comparing Autoencoder-Based and Pretrained Video Representations for VideoQA
description: Self-supervised video representation learning for VideoQA using autoencoders, pretrained features, and Qwen2-VL-7B.

remote_theme: just-the-docs/just-the-docs@v0.12.0

plugins:
  - jekyll-remote-theme

url: https://pgailinas.github.io
baseurl: /videoqa-representation-comparison

toc: false

ga_tracking: G-DWJVXLK3B3
ga_tracking_anonymize_ip: true

