title: Investigating Self-Supervised Autoencoder Learning for VideoQA
description: Self-supervised autoencoder learning for Video Question Answering (VideoQA).

remote_theme: just-the-docs/just-the-docs@v0.12.0

plugins:
  - jekyll-remote-theme

url: https://pgailinas.github.io
baseurl: /videoqa-representation-comparison

toc: false

ga_tracking: G-DWJVXLK3B3
ga_tracking_anonymize_ip: true

